### PR TITLE
bump ts deps

### LINKED ISSUE #65: Support `@typescript-eslint/parser` v7?

### PR DESCRIPTION
**Pull request by patricklx**
fixes #65 

is this a breaking change?

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
we're compat with eslint-plugin-ember -- so.. no?

my main worry was

  "@typescript-eslint/scope-manager":

but https://github.com/typescript-eslint/typescript-eslint/blob/main/CHANGELOG.md

it hasn't changed

**Review by NullVoxPopuli — APPROVED** [review]

**Comment by chancancode** [comment]
When you change the requirements of a peer dependency it is certainly a breaking change; it is not necessarily a problem if managed accordingly, and since this is pre 1.0, bumping minor is appropriate, which you did, so that's all good from this package's perspective.

However since this is a dependency of `eslint-plugin-ember`, that will become a problem when `eslint-plugin-ember` absorb this change, it would have to propagate the peer dependency requirement to its consumers (the apps), and it would have to bump major. `eslint-plugin-ember` is already missing that peer dependency declaration in its package.json currently.

Probably what needs to happen is:

* `@typescript-eslint/parser` should probably be an _optional_ peer dependency here
* Do we really need 7.x? Or does the code work with 6.x too?
  * If so, the dep range should be something like `^6.x.y || ^ 7.x.x`, and `eslint-plugin-ember` can propagate that requirement but wouldn't need to bump major
  * If not, is it feasible to make it work with both?
  * If we really can't, then `eslint-plugin-ember` should propagate that optional peer dep requirement and bump major

**Comment by patricklx** [comment]
It can be both, but thr typescript version must match as well

**Comment by chancancode** [comment]
> It can be both, but thr typescript version must match as well

Is that our constraint or is it `@typescript-eslint/parser`'s constraint?

It it's the latter, it's probably their responsibility to declare the proper peer dependency version range on TypeScript appropriately, and you'll run into other issues unrelated to this package if you didn't have the right combination.

If it's ours, then there is probably not a whole lot we can do in terms of expressing that aspect in the package.json dependency range, but perhaps we can throw a runtime error if we detect a mismatch?

**Comment by patricklx** [comment]
Yes, currently only do it for typescript, need to do it for other as well.
Like this:
https://github.com/ember-cli/eslint-plugin-ember/blob/4ea44596a33ee0d5c3cf331794adef137b53bbae/package.json#L126

**Pull request merged**
